### ISSUE TITLE
Can't get Lando recipe running

### ISSUE THREAD

**Issue by justageek** [Lullabot/ibm-dte#10]
I had a generic Drupal 8 Lando site running well, so I'm trying the recipe in the repo
Cloned the repo
Ran `lando start`

I got the Drupal install, but it said the database was already there, I suppose from my own setup.  So, I pruned all the docker containers and started over.  Now when I run the start command

`Warning: require(/app/web/../vendor/autoload.php): failed to open stream: No such file or directory in /app/web/autoload.php on line 17 Call Stack: 0.0040 397256 1. {main}() /app/web/index.php:0 0.0043 397528 2. require_once('/app/web/autoload.php') /app/web/index.php:14 Fatal error: require(): Failed opening required '/app/web/../vendor/autoload.php' (include_path='.:/usr/local/lib/php') in /app/web/autoload.php on line 17 Call Stack: 0.0040 397256 1. {main}() /app/web/index.php:0 0.0043 397528 2. require_once('/app/web/autoload.php') /app/web/index.php:14 
`
If I'm missing a step locally, please let me know, but I see the lando yaml file, so everything looks like it is ready to go.  Here is my docker info

Client:
 Version:      18.03.1-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   9ee9f40
 Built:        Thu Apr 26 07:13:02 2018
 OS/Arch:      darwin/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.03.1-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.5
  Git commit:   9ee9f40
  Built:        Thu Apr 26 07:22:38 2018
  OS/Arch:      linux/amd64
  Experimental: true

**Comment by justageek** [comment]
I forgot the most critical step, running the composer install process.  So, I get this far
`
Generating autoload files
> DrupalProject\composer\ScriptHandler::createRequiredFiles
Script DrupalProject\composer\ScriptHandler::createRequiredFiles handling the post-install-cmd event terminated with an exception

                       
  [Exception]          
  invalid array index  
                       

install [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--no-suggest] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--ignore-platform-reqs] [--] [<packages>]...
`
Trying to navigate to the site produces a white screen of death, probably because the autoload files are busted.

**Comment by justageek** [comment]
This appears to pertain to what I'm seeing:
https://github.com/drupal-composer/drupal-project/issues/391

Note that when I ssh into the server, the vi editor doesn't appear to be available, or maybe just not in my path.

**Comment by q0rban** [comment]
@justageek can you try:

```
lando destroy
rm -r vendor web/core web/modules/contrib
lando start
```

**Comment by justageek** [comment]
I believe that fixes it, thanks.
