### ISSUE TITLE
Ensure Paragraph entity data is properly serialized for jsonapi entity endpoints.

### ISSUE THREAD

**Issue by justageek** [Lullabot/ibm-dte#17]
## Scope
Validate serialized paragraph data that is attached to an entity revision.

When getting an individual node entity revision where the node bundle includes one or more configured Paragraph entities,  ensure the correct paragraph entity data is properly serialized in the resulting json data for the node entity revision.

## Testing Setup
 - Create a Paragraph type with one or more fields.
 - Add a field to the Article node bundle to be used for attaching the Paragraph entities.
 - Enable Content Moderation and ensure the Article bundle is able to be used with a moderation workflow.

## Test
 - Create an Article node and populate with one or more Paragraph entities.
 - Edit the Article node and create a new revision
 -- Modify the paragraph field data
 -- Attach an additional paragraph entity
 -- Change the workflow state.
 - Navigate to /jsonapi/node/article
 - Navigate to the jsonapi rest endpoint to load the individual article node.
 - Load the Article node revision
 - Ensure the paragraph entity data included with the new revision reflects the correct state of the revision's paragraph entity data.

**Comment by e0ipso** [comment]
I am very confident that JSON API can handle paragraphs. What we need to ensure is that the revision work we have done can produce the expected results. That is, it outputs the latest version of the article node, and the latest version of all the included paragraphs.
