### ISSUE TITLE
Add Functional test coverage for new http api parameters.

### ISSUE THREAD

**Issue by justageek** [Lullabot/ibm-dte#18]
The resource_version query parameter requires functional test coverage.  The valid values currently supported are:
- rel:working-copy
- rel:latest-version
- id:<integer revision id>

## Tests
 - The rel:working-copy should load the working copy (current revision to Drupal)
 - The rel:latest-version should load the latest version of the entity (latest revision to Drupal)
 - the id:<revision id> should load the specific revision id corresponding to the id value passed.  
 - The revision entity loaded by id must belong to the correct parent entity, i.e. one cannot load a revision by id value for an entity that does match the current UUID value in the requested route.
 - Validate the serialized json to ensure it is correct for the revision being loaded in the test.
 - Validate that invalid parameter values throw the proper exceptions.

**Comment by sethlbrown** [comment]
This is still missing. It's been started but we should create more testing. While it is good that the plumbing is working we also want to make that actual changes on revisions show up with the correct parameters. Right now the testing isn't minimal, but Mateu doesn't believe it's sufficient.

@Snugug would be fine with manual testing and smoke screen automated testing. Don't feel like we need to get into heavy testing. Okay with community working this out.
