### ISSUE TITLE
fix: use tagged release for fieldable_path when available

### ISSUE THREAD

**Issue by e0ipso** [Lullabot/ibm-dte#23]
We are relying on the `-dev` release of `fieldable_path` at the moment. This is because the fixes we need have been committed but not released as a tagged version.

When they are released we should update `composer.json` to point to `1.0@RC`.

**Comment by e0ipso** [comment]
I reached out to the module maintainer to get this moving.

**Comment by e0ipso** [comment]
According to Ev he can do it any time, however he'd like to get confirmation about the fix. We need to:

1. Test that the issue @Snugug was seeing is gone.
2. Reach out to get a version tagged.
3. Update our `composer.json`.

**Comment by Snugug** [comment]
I've got the latest versions working in my repo!
