### ISSUE TITLE
Patch JSON API to allow loading revisions for individual requests

### ISSUE THREAD

**Issue by e0ipso** [Lullabot/ibm-dte#5]
## Problem

Once clients can discover revisions and we have a way to tell Drupal we want a particular revision, we need to load that specific revision instead of _current_.

## Proposed resolution

Decorate `paramconverter.jsonapi.entity_uuid` so request for individual entities load the appropriate revision. The consumer specifies the revision via the URL as per #3.

This service should be sent as a patch to JSON API Extras (so we can use it today) and to JSON API 2.x (so we stay forward compatible).

## Notes

This only affects individual entities, not collections. Collections are handled elsewhere.

**Comment by e0ipso** [comment]
Progress for this is being tracked in https://www.drupal.org/project/jsonapi/issues/2992833.

**Comment by Snugug** [comment]
I've got the latest versions working in my repo!
